set_property -dict { PACKAGE_PIN P17   IOSTANDARD LVCMOS33} [get_ports FPGA_CLK_100]
set_property -dict { PACKAGE_PIN P5   IOSTANDARD LVCMOS33 } [get_ports RESET_N]
set_property -dict { PACKAGE_PIN K2   IOSTANDARD LVCMOS33 } [get_ports LEDS[0]]
set_property -dict { PACKAGE_PIN J2   IOSTANDARD LVCMOS33 } [get_ports LEDS[1]]
set_property -dict { PACKAGE_PIN J3   IOSTANDARD LVCMOS33 } [get_ports LEDS[2]]
set_property -dict { PACKAGE_PIN H4   IOSTANDARD LVCMOS33 } [get_ports LEDS[3]]
set_property -dict { PACKAGE_PIN J4   IOSTANDARD LVCMOS33 } [get_ports LEDS[4]]
set_property -dict { PACKAGE_PIN G3   IOSTANDARD LVCMOS33 } [get_ports LEDS[5]]
set_property -dict { PACKAGE_PIN G4   IOSTANDARD LVCMOS33 } [get_ports LEDS[6]]
set_property -dict { PACKAGE_PIN F6   IOSTANDARD LVCMOS33 } [get_ports LEDS[7]]
set_property -dict { PACKAGE_PIN P4   IOSTANDARD LVCMOS33 } [get_ports led_mode]